language: java
install: true

jdk:
- openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
- cd legacy2oml

script:
  - ./gradlew build

deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    dry-run: false
    on:
      tags: true
      repo: jpl-imce/opencaesar-adapter
      branch: master