language: java
install: true

jdk:
- openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
- cd opencaesar-adapter

script:
  - ./gradlew build

deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    dry-run: false
    on:
      tags: true
      repo: JPL-IMCE/opencaesar-adapter
      branch: master
